controller_manager:
  ros__parameters:
    use_sim_time: False
    update_rate: 400  # Hz
    thread_priority: 40
    cpu_affinity: [1, 2, 3]

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - rh_r1_joint

    allow_nonzero_velocity_at_trajectory_end: true
    
    interface_name: position

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity
