enable_optimizer: true
enable_actions_concat: true
enable_spline: true
enable_temporal_ensemble: false
temporal_ensemble_coeff: 0.9
action_dim: 7
chunk_size: 100
n_action_step: 100 # 100
blending_horizon: 10 # 10
len_delay_time: 5 # 5
spline: "quintic" # "quintic" or "cubic" or "linear"
optimizer_solver: "CLARABEL"
policy_dir: "throwing_ball-act_chunk-size-100_epoch-200000/step-30000"
dataset_dir: "throwing_ball"
enable_actions_publish: True

